#!/bin/bash

SCRIPTPATH=$(cd "$(dirname "$0")"; pwd)

ln -s "$SCRIPTPATH/tmux.conf" ~/.tmux.conf 
ln -s "$SCRIPTPATH/vim" ~/.vim 
ln -s "$SCRIPTPATH/vimrc" ~/.vimrc
ln -s "$SCRIPTPATH/bash_aliases" ~/.bash_aliases
ln -s "$SCRIPTPATH/gitconfig" ~/.gitconfig
